# Tables and Variables
## February 2025

# Packages

In [1]:
import json
import csv
import pandas as pd
import string
import networkx as nx
from pyvis.network import Network
import d3graph

# Import Data

In [2]:
# Define file path
file_path = "01_raw/acs2023_1yr_variables_LABEL_CONCEPT_Btables.json"

# Load the JSON data from file
with open(file_path, "r", encoding="utf-8") as file:
    data = json.load(file)

In [3]:
data_product = pd.read_excel('01_raw/2023_DataProductList.xlsx', sheet_name='2023 Data Product List')
data_product = data_product[data_product['Data Product Type'] == 'Detailed Table']

In [4]:
data_product

,Table ID,Table Title,Table Universe,Data Product Type,Year,1-Year Geography Restrictions\n(with Summary Levels in Parentheses),5-Year Geography Restrictions\n(with Summary Levels in Parentheses)
0,B01001,Sex by Age,Total population,Detailed Table,"1,5",NaN,NaN
1,B01001A,Sex by Age (White Alone),People who are White alone,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
2,B01001B,Sex by Age (Black or African American Alone),People who are Black or African American alone,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
3,B01001C,Sex by Age (American Indian and Alaska Native ...,People who are American Indian and Alaska Nati...,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
4,B01001D,Sex by Age (Asian Alone),People who are Asian alone,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
...,...,...,...,...,...,...,...
1439,C27014,Public Health Insurance by Work Experience,Civilian noninstitutionalized population 19 to...,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
1440,C27016,Health Insurance Coverage Status by Ratio of I...,Civilian noninstitutionalized population for w...,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
1441,C27017,Private Health Insurance by Ratio of Income to...,Civilian noninstitutionalized population for w...,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
1442,C27018,Public Health Insurance by Ratio of Income to ...,Civilian noninstitutionalized population for w...,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...
1443,C27021,Health Insurance Coverage Status by Living Arr...,Civilian noninstitutionalized population,Detailed Table,"1,5",NaN,Excludes Place/Remainder and Block Group geogr...

# Labels and Concepts

## Labels

In [5]:
# Dictionary to store distinct labels for each table
table_labels = {}

# Process each variable in the dataset
for variable, details in data.items():
    table_id = variable.split("_")[0]  # Extract table ID
    label = details["label"]  # Extract label

    # Initialize table entry if not present
    if table_id not in table_labels:
        table_labels[table_id] = set()

    # Add label to the set to ensure uniqueness
    table_labels[table_id].add(label)

# Convert sets to lists for JSON serialization
formatted_labels = {"tables": []}
for table_id, labels in table_labels.items():
    formatted_labels["tables"].append({
        "table_id": table_id,
        "labels": list(labels)
    })

all_labels = set()

# Collect labels from all tables
for details in data.values():
    temp_labels = details["label"].split("!!")
    temp_labels = [label.translate(str.maketrans('', '', string.punctuation)) for label in temp_labels]
    all_labels.update(temp_labels)

# Convert set to sorted list for consistency
distinct_labels = sorted(list(all_labels))

## Concepts

In [6]:

# Dictionary to store distinct labels for each table
table_concepts = {}

# Process each variable in the dataset
for variable, details in data.items():
    table_id = variable.split("_")[0]  # Extract table ID
    concept = details["concept"]  # Extract label

    # Initialize table entry if not present
    if table_id not in table_concepts:
        table_concepts[table_id] = set()

    # Add label to the set to ensure uniqueness
    table_concepts[table_id].add(label)

# Convert sets to lists for JSON serialization
formatted_concepts = {"tables": []}
for table_id, concept in table_concepts.items():
    formatted_labels["tables"].append({
        "table_id": table_id,
        "concept": list(labels)
    })

all_concepts = set()

# Collect concepts from all tables
for details in data.values():
    all_concepts.add(details["concept"])

# Convert set to sorted list for consistency
distinct_concepts = sorted(list(all_concepts))

In [7]:
pd.Series(distinct_concepts).to_csv("02_review/distinct_concepts.csv", index=False)

## Labels to Variables

In [8]:
# variables = {
#     "Acreage and Agricultural Sales": , 
#     "Age": , 
#     "Ancestry":, 
#     "Commuting/Journey to Work":, 
#     "Computer and Internet Use":, 
#     "Disability":, 
#     "Educational Attainment":, 
#     "Undergraduate Field of Degree":, 
#     "Employment Status":, 
#     "Relationship to Householder":, 
#     "Fertility":, 
#     "Food Stamps Benefit":, 
#     "Grandparents as Caregivers":, 
#     "Health Insurance Coverage":, 
#     "Race":, 
#     "Hispanic or Latino Origin":, 
#     "Home Heating Fuel":, 
#     "Housing Costs for Owners":, 
#     "Income":, 
#     "Industry":, 
#     "Occupation":, 
#     "Class of Worker":, 
#     "Language Spoken at Home":, 
#     "Marital Status/Marital History":, 
#     "Home Ownership":, 
#     "Home Value":, 
#     "Rent":, 
#     "Place of Birth":, 
#     "Citizenship":, 
#     "Year of Entry":, 
#     "Plumbing Facilities":, 
#     "Kitchen Facilities":, 
#     "Telephone Service":, 
#     "Residence 1 Year Ago/Migration":, 
#     "School Enrollment":, 
#     "Sex":, 
#     "Units in Structure Rooms Bedrooms":, 
#     "Vehicles Available":, 
#     "Veteran Status":, 
#     "Work Status Last Year":, 
#     "Year Built":, 
#     "Year Moved In":
# }

In [9]:
universes = ['young adults aged 19 to 25', '(Hispanic or latino', 'Citizen, Voting-Age Population', 'Females 15 to 50 Years', 'Population 3 Years and Over', 'Population 25 Years and Over', 'Population 5 Years and Over', 'Civilian Noninstitutionalized Population', 'Full-Time, Year-Round Civilian Employed Population 16 Years and Over',
            'Civilian Employed Population 16 Years and Over', 'Owner-Occupied Housing Units']

In [10]:
# mapping of labels to variables
large_map = {
    "Acreage and Agricultural Sales":    ['acre', "acreage and agricultural sales"], 
    "Age":                               ['16 to 19 years', '20 to 24 years', '25 to 44 years', '45 to 54 years', 
                                          '55 to 59 years', '60 to 64 years', '65 years and over',
                                          '1 to 4 years', '5 to 17 years', '18 and 19 years ', 
                                          '20 to 24 years', '25 to 29 years', '30 to 34 years', 
                                          '35 to 39 years', '40 to 44 years', '45 to 49 years', 
                                          '50 to 54 years', '55 to 59 years', '60 to 64 years', 
                                          '65 to 69 years', '70 to 74 years', '75 years and over', 
                                          '35 to 44 years', '45 to 54 years', 'Age', '18 to 24 years', '25 to 34 years', 
                                          '55 to 64 years', '65 to 74 years', '75 to 84 years', '85 years and over',
                                          'under 15 years', '15 to 17 years', 'under 19 years', 'Age'], 
    "Ancestry":                          ['People Reporting Single Ancestry', 'People Reporting Multiple Ancestry', 
                                          'People Reporting Ancestry', 'Ancestry', "Ancestry not reported", 
                                          "Ancestry not specified", "Ancestry specified", "Ancestry unclassified"], 
    "Commuting/Journey to Work":         ['car', 'truck', 'van', 'car, truck, or van', 
                                          'bus', 'subway', 'elevated rail', 
                                          'long distance train', 'commuter rail', 
                                          'light rail', 'streetcar', 'trolley', 
                                          'ferryboat', 'taxi', 'ride-hailing service', 
                                          'motorcycle', 'bicycle', 'walked', 
                                          'worked at home', 'other method',
                                          'travel time to work',
                                          'time of departure to go to work', 'Time arriving at work',
                                          "commuting/journey to work", "means of transportation", "public transport", "walked"], 
    "Computer and Internet Use":         ['Computers in Household', 'Internet Subscription', 
                                          'Presence of a Computer', 'Computer Ownership', 
                                          'Internet Subscription', 'Internet Access', 'Computer Type', "computer and internet use"], 
    "Disability":                        ['Disability Status', 'Hearing Difficulty', 'Vision Difficulty', 
                                          'Cognitive Difficulty', 'Ambulatory Difficulty', 'Self-Care Difficulty', 
                                          'Independent Living Difficulty', 'Number of Disabilities', 'Disability'], 
    "Educational Attainment":            ['grade 1 to grade 4', 'grade 5 to grade 8', 
                                          'grade 9 to grade 12', 'Enrolled in kindergarten',
                                          'Enrolled in school', 'Enrolled in nursery school', 
                                          'undergraduate years', 'graduate or professional school', 
                                          'not enrolled in school', 'no diploma',
                                          'Less than 9th grade', '9th to 12th grade, no diploma', 
                                          'high school graduate', 'some college, no degree', 
                                          "associate's degree", "bachelor's degree", 
                                          'graduate or professional degree', 'no schooling completed', 
                                          'nursery to 4th grade', '5th and 6th grade', 
                                          '7th and 8th grade', '9th grade', '10th grade', 
                                          '11th grade', '12th grade', 'high school graduate', 
                                          'some college',  "associate's degree", 
                                          "bachelor's degree", "master's degree", 
                                          'professional school degree', "doctorate degree", 
                                          'Regular high school diploma', 'GED or alternative credential', 
                                          'Educational Attainment'], 
    "Undergraduate Field of Degree":     ["Detailed Field of Bachelor's Degree", "Fields of Bachelor's Degrees", 'first major',
                                          'Field of degree'], 
    "Employment Status":                 ['Employment Status', 'Unemployed', 'Not in Labor Force', 
                                          'Civilian Labor Force', 'In labor force', 'Employed',
                                          'Work Status'], 
    "Relationship to Householder":       ['Relationship to Householder', 'Living Arrangement',
                                          'Grandparent householder',
                                          'Household Type', 'Family Type', 'Cohabiting Couple Households',
                                          'Coupled Households by Type', 'Nonfamily Households',
                                          'Subfamily Type', 'Households by Presence of Nonrelatives',
                                          'Multigenerational Households', 'Unrelated Individuals', 'Families'], 
    "Fertility":                         ['Birth in the Past 12 Months', 'fertility'], 
    "Food Stamps Benefit":               ['Food Stamps/SNAP', 'SNAP', "food stamps"], 
    "Grandparents as Caregivers":        ['Grandparents Living With Own Grandchildren',
                                          'Grandparents Responsible for Own Grandchildren'], 
    "Health Insurance Coverage":         ['Health Insurance Coverage', 'Health Insurance Status',
                                          'Health Insurance', 'Medicare Coverage', 'Medicaid/Means-Tested Public Coverage'
                                          'TRICARE/Military Health Coverage', 'VA Health Care', 'insured', 'uninsured', 
                                          'public health insurance', 'private health insurance'], 
    "Race":                              ['American Indian', 'Alaskan Native', 'Asian', 
                                          'Black or African American', 'Native Hawaiian and Other Pacific Islander', 'White',
                                          'Black Alone', 'Alaska Native', 'Some Other Race', 'Two or More Races'], 
    "Hispanic or Latino Origin":         ['Hispanic or Latino Origin', "(Hispanic or Latino"], 
    "Home Heating Fuel":                 ['House Heating Fuel', "fuel oil", "natural gas", "electricity", "wood", "coal", "other fuel"], 
    "Housing Costs for Owners":          ['Homeowners Insurance Costs', 'Fuel Costs', 'Electricity Costs', 
                                          'Gas Costs', 'Water and Sewer Costs', 'Other Fuel Costs',
                                          'Monthly Owner Costs', 'Real Estate Taxes', 'Mortgage Status'],
    "Rent":                              ['Rent'], 
    "Income":                            ['Income', 'Earnings in the Past 12 Months', 'Aggregate Earnings', 'Median Earnings',
                                           "median income", "per capita income", "household income"], 
    "Industry":                          ['Agriculture, forestry, fishing and hunting, and mining', 'Industry'], 
    "Occupation":                        ['Agricultural inspectors', 'Detailed Occupation', 'Occupation'], 
    "Class of Worker":                   ['Class of Worker'], 
    "Language Spoken at Home":           ['Language and Ability to Speak English', 'Language Spoken at Home',
                                          'Detailed Household Language'], 
    "Marital Status/Marital History":    ['Marital Status', 'First Marriage', 'Divorced in the Past 12 Months'
                                          'Married in the Past 12 Months', 'Widowed in the Past 12 Months', 'times married', 
                                          'year last married',], 
    "Home Ownership, Home Value":        ['Mortgage Status', 'Housing Costs', 'Median Value', 'Price Asked', 'home value'], 
    "Place of Birth":                    ['Place of Birth', 'World Region of Birth', 'Nativity', 'foreign born', 'native'], 
    "Citizenship":                       ["US citizen born ",
                                          "US citizen born abroad of American parents",
                                          "US citizen born in Puerto Rico",
                                          "US citizen born in Puerto Rico or US Island Areas",
                                          "US citizen born in US or US Island Areas",
                                          "US citizen by naturalization",
                                          "Naturalized US citizen", "Not a US citizen",
                                          'Citizenship Status', 'Year of naturalization'], 
    "Year of Entry":                     ['Year of Entry'], 
    "Plumbing Facilities":               ['Plumbing'], 
    "Kitchen Facilities":                ['Kitchen'], 
    "Telephone Service":                 ['Telephone Service'], 
    "Residence 1 Year Ago/Migration":    ['living in area 1 year ago', 'Geographical Mobility in the Past Year'], 
    "School Enrollment":                 ['School Enrollment'], 
    "Sex":                               ['Sex', 'male', 'female'], 
    "Units in Structure Rooms Bedrooms": ['Units in Structure', 'Structure Type', 'Bedrooms', 'Rooms'], 
    "Vehicles Available":                ['Private Vehicle', 'Vehicles Available'], 
    "Veteran Status":                    ['Veteran Status', 'veteran', 'nonveteran'],
    "Work Status Last Year":             ['Work Experience', 'Work Status', 'Usual Hours Worked', 'Weeks Worked'], 
    "Year Built":                        ['Year Structure Built', 'year built'], 
    "Year Moved In":                     ['Year Householder Moved Into Unit', 'Tenure', 'year moved in'],
    "Vacancy":                           ['Vacancy Status', 'Vacancy Duration'],
    "Poverty":                           ['Poverty']
}

In [11]:
variable_map = {
    'Age': ['16 to 19 years', '20 to 24 years', '25 to 44 years', '45 to 54 years', '55 to 59 years', '60 to 64 years', '65 years and over', '1 to 4 years', '5 to 17 years', '18 and 19 years ', '20 to 24 years', '25 to 29 years', '30 to 34 years', '35 to 39 years', '40 to 44 years', '45 to 49 years', '50 to 54 years', '55 to 59 years', '60 to 64 years', '65 to 69 years', '70 to 74 years', '75 years and over', '35 to 44 years', '45 to 54 years', 'Age', '18 to 24 years', '25 to 34 years', '55 to 64 years', '65 to 74 years', '75 to 84 years', '85 years and over', 'under 15 years', '15 to 17 years', 'under 19 years', 'Age'], 
    'Sex': ['Sex', 'male', 'female'],
    'Race': ['American Indian', 'Alaskan Native', 'Asian', 'Black or African American', 'Native Hawaiian and Other Pacific Islander', 'White', 'Black Alone', 'Alaska Native', 'Some Other Race', 'Two or More Races'],
    'Hispanic or Latino Origin': ['Hispanic or Latino Origin', "(Hispanic or Latino"],
    'Ancestry': ['Ancestry'],
    'Citizenship Status': ["US citizen born ", "US citizen born abroad of American parents", "US citizen born in Puerto Rico", "US citizen born in Puerto Rico or US Island Areas", "US citizen born in US or US Island Areas", "US citizen by naturalization", "Naturalized US citizen", "Not a US citizen", 'Citizenship Status', 'Year of naturalization'],
    'Year of Entry': ['Year of Entry'],
    'Foreign Born Place of Birth': ['Place of Birth', 'World Region of Birth', 'Nativity', 'foreign born', 'native'],
    'Migration/Residence 1 Year Ago': ['living in area 1 year ago', 'Geographical Mobility in the Past Year'],
    'Commuting/Journey to Work': ['car', 'truck', 'van', 'car, truck, or van', 'bus', 'subway', 'elevated rail', 'long distance train', 'commuter rail', 'light rail', 'streetcar', 'trolley', 'ferryboat', 'taxi', 'ride-hailing service', 'motorcycle', 'bicycle', 'walked', 'worked at home', 'other method', 'travel time to work', 'time of departure to go to work', 'Time arriving at work', "commuting/journey to work", "means of transportation", "public transport", "walked"],
    'Relationship to Householder': ['Relationship to Householder', 'Living Arrangement', 'Grandparent householder', 'Cohabiting Couple Households', 'Coupled Households by Type', 'Nonfamily Households', 'Households by Presence of Nonrelatives', 'Multigenerational Households', 'Unrelated Individuals', 'Families'],
    'Grandparents as Caregivers': ['own grandchildren'],
    'Household Type': ['Household Type', 'Family Type', 'Subfamily Type'],
    'Marital Status and History': ['Marital Status', 'First Marriage', 'Divorced in the Past 12 Months' 'Married in the Past 12 Months', 'Widowed in the Past 12 Months', 'times married', 'year last married'],
    'Fertility': ['Birth in the Past 12 Months', 'fertility'],
    'School Enrollment': ['School Enrollment'],
    'Educational Attainment': ['grade 1 to grade 4', 'grade 5 to grade 8', 'grade 9 to grade 12', 'Enrolled in kindergarten', 'Enrolled in school', 'Enrolled in nursery school', 'undergraduate years', 'graduate or professional school', 'not enrolled in school', 'no diploma', 'Less than 9th grade', '9th to 12th grade, no diploma', 'high school graduate', 'some college, no degree', "associate's degree", "bachelor's degree", 'graduate or professional degree', 'no schooling completed', 'nursery to 4th grade', '5th and 6th grade', '7th and 8th grade', '9th grade', '10th grade', '11th grade', '12th grade', 'high school graduate', 'some college',  "associate's degree", "bachelor's degree", "master's degree", 'professional school degree', "doctorate degree", 'Regular high school diploma', 'GED or alternative credential', 'Educational Attainment'],
    'Field of Degree': ["Detailed Field of Bachelor's Degree", "Fields of Bachelor's Degrees", 'first major', 'Field of degree'],
    'Language Spoken at Home': ['Language and Ability to Speak English', 'Language Spoken at Home', 'Detailed Household Language'],
    'Poverty': ['Poverty'],
    'Disability': ['Hearing Difficulty', 'Vision Difficulty', 'Cognitive Difficulty', 'Ambulatory Difficulty', 'Self-Care Difficulty', 'Independent Living Difficulty', 'Number of Disabilities', 'Disability'],
    'Income': ['Income', 'Earnings in the Past 12 Months', 'Aggregate Earnings', 'Median Earnings', "median income", "per capita income", "household income"],
    'Veteran Status': ['Veteran Status', 'veteran', 'nonveteran'],
    'Food Stamps/SNAP Beneft': ['Food Stamps/SNAP', 'SNAP', "food stamps"],
    'Employment Status': ['Employment Status', 'Unemployed', 'Not in Labor Force', 'Civilian Labor Force', 'In labor force', 'Employed', 'Work Status'],
    'Work Status Last Year': ['Work Experience', 'Work Status', 'Usual Hours Worked', 'Weeks Worked'],
    'Industry': ['Industry'],
    'Occupation': ['Occupation'],
    'Class of Worker': ['Class of Worker'],
    'Housing Characteristics': ['Vacancy Status', 'Vacancy Duration', 'Plumbing', 'Kitchen', 'Telephone Service', 'Year Structure Built', 'year built','Units in Structure', 'Structure Type', 'Bedrooms', 'Rooms'],
    'Health Insurance': ['Health Insurance', 'Medicare Coverage', 'Medicaid/Means-Tested Public Coverage', 'TRICARE/Military Health Coverage', 'VA Health Care', 'insured', 'uninsured'],
    'Computer and Internet Use': ['Computers', 'Computer', 'internet'],
    'Citizen Voting Age Population': ['Citizen, Voting-Age Population'],
    'Quality Measures': ['unweighted', 'coverage', 'response and nonresponse rates', 'overall person characteristic'] ,
    'Allocation': ['Allocation'], 
    'Computer and Internet Use': ['Computers in Household', 'Internet Subscription', 'Presence of a Computer', 'Computer Ownership', 'Internet Subscription', 'Internet Access', 'Computer Type', "computer and internet use"], 
    'Home Heating Fuel': ['House Heating Fuel', "fuel oil", "natural gas", "electricity", "wood", "coal", "other fuel"], 
    'Housing Costs for Owners': ['Homeowners Insurance Costs', 'Fuel Costs', 'Electricity Costs', 'Gas Costs', 'Water and Sewer Costs', 'Other Fuel Costs', 'Monthly Owner Costs', 'Real Estate Taxes', 'Mortgage Status'], 
    'Rent': ['Rent'], 
    'Home Ownership, Home Value': ['Mortgage Status', 'Housing Costs', 'Median Value', 'Price Asked', 'home value'], 
    'Vehicles Available': ['Private Vehicle', 'Vehicles Available'], 
    'Year Moved In': ['Year Householder Moved Into Unit', 'Tenure', 'year moved in'],
    'Group Quarters': ['Group Quarters'],
    'Puerto Rico': ['Puerto Rico']
}

question_map = {
    'Age': {'person': 4},
    'Sex': {'person': 5},
    'Race': {'person': 6},
    
}

## Concepts to Variables

In [12]:
# # Convert the dictionary into the requested JSON format
# formatted_output = {"tables": []}

# for table_id, details in table_variables.items():
#     formatted_output["tables"].append({
#         "table_id": table_id,
#         "variables": details["variables"]
#     })

table_data = data
table_variable_matches = {}
matching_keys = set()
unmatched_tables = []

for variable, details in table_data.items():
    table_id = variable.split("_")[0]
    concept = details["concept"].lower()
    label = details["label"].lower()

    for var, keywords in variable_map.items():
        if any(k.lower().strip() in concept or k.lower().strip() in label for k in keywords):
            matching_keys.add(var)

    if matching_keys:
        table_variable_matches[table_id] = list(matching_keys)
    else:
        unmatched_tables.append(table_id)

In [13]:
pd.DataFrame.from_dict(table_variable_matches, orient='index').reset_index(names = 'table')

,table,0,1,2,3,4,5,6,7,8,...,33,34,35,36,37,38,39,40,41,42
0,B01001,Sex,Age,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,B01001A,Sex,Race,Age,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,B01001B,Sex,Race,Age,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,B01001C,Sex,Foreign Born Place of Birth,Race,Age,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,B01001D,Sex,Foreign Born Place of Birth,Race,Age,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,B992708,Group Quarters,Class of Worker,Quality Measures,Work Status Last Year,Household Type,Field of Degree,Employment Status,Computer and Internet Use,School Enrollment,...,Grandparents as Caregivers,Hispanic or Latino Origin,Industry,Puerto Rico,Citizenship Status,Housing Characteristics,Housing Costs for Owners,Income,Language Spoken at Home,Health Insurance
1177,B992709,Group Quarters,Class of Worker,Quality Measures,Work Status Last Year,Household Type,Field of Degree,Employment Status,Computer and Internet Use,School Enrollment,...,Grandparents as Caregivers,Hispanic or Latino Origin,Industry,Puerto Rico,Citizenship Status,Housing Characteristics,Housing Costs for Owners,Income,Language Spoken at Home,Health Insurance
1178,B99281,Group Quarters,Class of Worker,Quality Measures,Work Status Last Year,Household Type,Field of Degree,Employment Status,Computer and Internet Use,School Enrollment,...,Grandparents as Caregivers,Hispanic or Latino Origin,Industry,Puerto Rico,Citizenship Status,Housing Characteristics,Housing Costs for Owners,Income,Language Spoken at Home,Health Insurance
1179,B99282,Group Quarters,Class of Worker,Quality Measures,Work Status Last Year,Household Type,Field of Degree,Employment Status,Computer and Internet Use,School Enrollment,...,Grandparents as Caregivers,Hispanic or Latino Origin,Industry,Puerto Rico,Citizenship Status,Housing Characteristics,Housing Costs for Owners,Income,Language Spoken at Home,Health Insurance
1180,B99283,Group Quarters,Class of Worker,Quality Measures,Work Status Last Year,Household Type,Field of Degree,Employment Status,Computer and Internet Use,School Enrollment,...,Grandparents as Caregivers,Hispanic or Latino Origin,Industry,Puerto Rico,Citizenship Status,Housing Characteristics,Housing Costs for Owners,Income,Language Spoken at Home,Health Insurance

# Export

In [15]:
# Define output file path
json_export_file_path = "02_review/table_variable_matches.json"

# # Save the extracted labels to a new JSON file
# with open(labels_output_file_path, "w", encoding="utf-8") as outfile:
#     json.dump(formatted_labels, outfile, indent=4)
    


# # Save the extracted concepts to a new JSON file
# with open(concepts_output_file_path, "w", encoding="utf-8") as outfile:
#     json.dump(formatted_concepts, outfile, indent=4)


# Save the formatted data to a new JSON file
with open(json_export_file_path, "w", encoding="utf-8") as outfile:
    json.dump(table_variable_matches, outfile, indent=4)

txt_export_file_path = "02_review/table_variable_matches.txt"

with open(txt_export_file_path, "w", encoding="utf-8") as outfile:
    json.dump(table_variable_matches, outfile, indent=4)

# Charting

Groupings -> Table, Variable, Universe

## networkx

In [ ]:
G = nx.Graph()

# Add nodes and edges
for table_id, variables in table_variable_matches.items():
    G.add_node(table_id, color="blue", size=10)
    for var in variables:
        G.add_node(var, color="red", size=15)

# Create interactive visualization
net = Network(notebook=True, height="750px", width="100%")
net.from_nx(G)
net.show("network_chart.html")

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.

TypeError: Network.show() got an unexpected keyword argument 'cdn_resources'

## d3graph

In [17]:
edges = []
for table_id, variables in table_variable_matches.items():
    for var in variables:
        edges.append([var, table_id])

# Convert to DataFrame
df_edges = pd.DataFrame(edges, columns=["target", "source"])

# Convert edge list to adjacency matrix
adj_matrix = df_edges.pivot_table(index="source", columns="target", aggfunc=lambda x: 1, fill_value=0)

# Convert to binary adjacency (d3graph requires square format)
adj_matrix = adj_matrix.reindex(index=adj_matrix.index.union(adj_matrix.columns), 
                                columns=adj_matrix.index.union(adj_matrix.columns), 
                                fill_value=0)

In [18]:

# Create D3 graph
d3 = d3graph.d3graph(charge=250, collision=5)
d3.graph(adj_matrix)
# Set node properties (size, color)
node_counts = df_edges["source"].value_counts()
node_sizes = {node: min(count * 3, 50) for node, count in node_counts.items()}  
d3.set_node_properties(color='cluster', size = 10)


# Show
d3.show(filepath="d3_network.html")

[d3graph] INFO> Set directed=True to see the markers!
[d3graph] INFO> Keep only edges with weight>0
[d3graph] INFO> Converting source-target into adjacency matrix..
[d3graph] INFO> Making the matrix symmetric..
[d3graph] INFO> Converting adjacency matrix into source-target..
[d3graph] INFO> Number of unique nodes: 1224
[d3graph] INFO> Converting adjacency matrix into source-target..
[d3graph] INFO> Number of unique nodes: 1224
[d3graph] INFO> Slider range is set to [0, 1]
[d3graph] INFO> Write to path: [C:\Users\Garet\AppData\Local\Temp\tmpifrmx28k\d3_network.html]
[d3graph] INFO> File already exists and will be overwritten: [C:\Users\Garet\AppData\Local\Temp\tmpifrmx28k\d3_network.html]

In [19]:
adj_matrix

,Age,Allocation,Ancestry,B01001,B01001A,B01001B,B01001C,B01001D,B01001E,B01001F,...,Race,Relationship to Householder,Rent,School Enrollment,Sex,Vehicles Available,Veteran Status,Work Status Last Year,Year Moved In,Year of Entry
Age,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Allocation,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ancestry,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
B01001,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
B01001A,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vehicles Available,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Veteran Status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Work Status Last Year,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Year Moved In,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Year of Entry,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df_edges['source'].unique()

array(['B01001', 'B01001A', 'B01001B', ..., 'B99281', 'B99282', 'B99283'],
      dtype=object)